name: Executar Script Python a cada 15 minutos

on:
  schedule:
    # Executa o script a cada 15 minutos
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Adiciona a opção de execução manual

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixa o repositório
      - name: Check out the repository
        uses: actions/checkout@v3

      # Passo 2: Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Passo 3: Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openai yagmail pywhatkit openpyxl

      # Passo 4: Configura variáveis de ambiente
      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "FIRELIES_API_KEY=${{ secrets.FIRELIES_API_KEY }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      # Passo 5: Executa o script
      - name: Run the Python script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FIRELIES_API_KEY: ${{ secrets.FIRELIES_API_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python script.py
